system {
    host-name sto-dc1-bdr-leaf-1;
    domain-name dc.example.com;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password "$6$obfuscated";
            }
        }
    }
    services {
        ssh;
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 10.100.0.4/24;
            }
        }
    }
}
routing-options {
    static {
        route 0.0.0.0/0 next-hop 10.100.0.254;
    }
}
