system {
    host-name sto-dc1-bdr-leaf-1;
    domain-name dc.example.com;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password "$6$obfuscated";
            }
        }
    }
    services {
        ssh;
    }
}
policy-options {
    policy-statement EXPORT-TO-INTERNET {
        term dc-prefixes {
            from {
                route-filter 10.100.0.0/16 orlonger;
            }
            then accept;
        }
        term default {
            then reject;
        }
    }
}
protocols {
    bgp {
        group EBGP-UPSTREAM {
            type external;
            peer-as 65002;
            neighbor 10.0.0.5 {
                description "Internet-Router";
                export EXPORT-TO-INTERNET;
            }
        }
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 10.100.0.4/24;
            }
        }
    }
    xe-0/0/0 {
        description "UPLINK-sto-dc1-core-1-xe0/0/48";
        unit 0 {
            family inet {
                address 10.0.0.4/30;
            }
        }
    }
    xe-0/0/1 {
        description "EBGP-External-AS65001-primary";
        unit 0 {
            family inet {
                address 10.0.0.6/30;
            }
        }
    }
    xe-0/0/2 {
        description "EBGP-External-AS65001-secondary";
        unit 0 {
            family inet {
                address 10.0.0.10/30;
            }
        }
    }
}
routing-options {
    router-id 10.100.0.4;
    autonomous-system 65001;
    static {
        route 0.0.0.0/0 next-hop 10.100.0.254;
    }
}
