hostname sto-dc1-dist-2
!
ip domain-name dc.example.com
!
aaa new-model
username admin privilege 15 secret 9 $9$obfuscated
!
interface Management0
 description OOB-Management
 ip address 10.100.0.3 255.255.255.0
 no shutdown
!
interface GigabitEthernet1/0/1
 description UPLINK-sto-dc1-core-1-Gi1/0/3
 no switchport
 no shutdown
!
interface GigabitEthernet1/0/2
 description DOWNLINK-Access-rack-B
 no shutdown
!
interface GigabitEthernet1/0/3
 description DOWNLINK-Access-rack-B
 no shutdown
!
ip route vrf Mgmt-vrf 0.0.0.0 0.0.0.0 10.100.0.254
!
line vty 0 4
 login local
 transport input ssh
!
end
