hostname sto-office1-core-1
!
ip domain-name office.example.com
!
username admin privilege 15 secret 9 $9$obfuscated
!
interface GigabitEthernet1/0/1
 description UPLINK-ISP-Edge-Router
 no switchport
 ip address 10.10.0.1 255.255.255.252
 no shutdown
!
interface GigabitEthernet1/0/2
 description DOWNLINK-sto-office1-dist-1
 no switchport
 ip address 10.10.1.1 255.255.255.252
 no shutdown
!
interface GigabitEthernet1/0/3
 description DOWNLINK-sto-office1-dist-2-Core-Link
 no switchport
 ip address 10.10.1.5 255.255.255.252
 no shutdown
!
ip route 0.0.0.0 0.0.0.0 10.10.0.2
!
line vty 0 4
 transport input ssh
!
end
