hostname ams-dc1-oob-1
!
ip domain-name dc.example.com
feature ssh
feature telnet
!
username admin password 7 obfuscated role network-admin
!
interface mgmt0
  description OOB-Management
  ip address 10.200.0.10/24
  no shutdown
!
vrf context management
  ip route 0.0.0.0/0 10.200.0.254
!
