hostname ams-dc1-oob-1
!
ip domain-name dc.example.com
feature ssh
feature lacp
feature lldp
!
username admin password 7 obfuscated role network-admin
!
interface mgmt0
  description OOB-Management
  ip address 10.200.0.10/24
  no shutdown
!
interface Ethernet1/1
  description UPLINK-ams-dc1-core-1-xe0/0/47
  no shutdown
!
interface Ethernet1/2
  description DOWNLINK-OOB-console-servers
  no shutdown
!
interface Ethernet1/3
  description DOWNLINK-OOB-console-servers
  no shutdown
!
vrf context management
  ip route 0.0.0.0/0 10.200.0.254
!
