hostname ams-dc1-oob-1
!
ip domain-name dc.example.com
feature ssh
feature lacp
feature lldp
!
username admin password 7 obfuscated role network-admin
!
vlan 300
  name MANAGEMENT
vlan 999
  name OOB-NATIVE
!
interface mgmt0
  description OOB-Management
  ip address 10.200.0.10/24
  no shutdown
!
interface Ethernet1/1
  description UPLINK-ams-dc1-core-1-xe0/0/47
  switchport mode trunk
  switchport trunk allowed vlan 300,999
  no shutdown
!
interface Ethernet1/2
  description DOWNLINK-OOB-console-servers
  switchport mode access
  switchport access vlan 999
  no shutdown
!
interface Ethernet1/3
  description DOWNLINK-OOB-console-servers
  switchport mode access
  switchport access vlan 999
  no shutdown
!
interface Vlan300
  description MANAGEMENT-GW
  ip address 10.200.0.11/24
  no shutdown
!
vrf context management
  ip route 0.0.0.0/0 10.200.0.254
!
