"""initial schema

Revision ID: a9222fcfea74
Revises:
Create Date: 2026-08-27 14:05:42.335224

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9222fcfea74"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("vendor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("serial_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("os", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("os_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hardware_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ned_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assetcluster",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ned_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collectionagent",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("last_manifest_poll", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("acked_revision", sa.Integer(), nullable=False),
        sa.Column("acked_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contact",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("family_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contactassignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("site_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credential",
        sa.Column("credential_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vault_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credential_name"), "credential", ["name"], unique=True)
    op.create_table(
        "device_config",
        sa.Column("node_instance_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_config_created_at"), "device_config", ["created_at"], unique=False)
    op.create_index(op.f("ix_device_config_hash"), "device_config", ["hash"], unique=False)
    op.create_index(op.f("ix_device_config_node_instance_id"), "device_config", ["node_instance_id"], unique=False)
    op.create_table(
        "externalvalue",
        sa.Column("attr_ptr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ev_type", sa.Enum("data", "resource", name="evtype"), nullable=False),
        sa.Column("plugin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("attr_ptr"),
    )
    op.create_table(
        "logicalnode",
        sa.Column("hostname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("site", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ned",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "region",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "siteregionassignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("site_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assetclusterlink",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["assetcluster.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "cluster_id"),
    )
    op.create_table(
        "collectionagentmatchrule",
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("site", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("vendor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("os", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_agent_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_agent_id"],
            ["collectionagent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credentialfield",
        sa.Column("field_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.Integer(), nullable=False),
        sa.Column("field_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credential.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credentialfield_credential_id"), "credentialfield", ["credential_id"], unique=False)
    op.create_table(
        "node",
        sa.Column("asset_ref_id", sa.Integer(), nullable=False),
        sa.Column("asset_ref_type", sa.Enum("asset", "asset_cluster", name="assetreftype"), nullable=False),
        sa.Column("logical_node_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("planned", "init", "active", "decommissioned", name="nodestatus"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["logical_node_id"],
            ["logicalnode.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_node_created_at"), "node", ["created_at"], unique=False)
    op.create_table(
        "sitecredential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credential_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credential.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sitecredential_credential_id"), "sitecredential", ["credential_id"], unique=False)
    op.create_index(op.f("ix_sitecredential_site_name"), "sitecredential", ["site_name"], unique=False)
    op.create_table(
        "telemetryagent",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("snmp_version", sa.Enum("v2c", "v3", "both", name="snmpversion"), nullable=False),
        sa.Column("snmp_trap_port", sa.Integer(), nullable=False),
        sa.Column("syslog_port", sa.Integer(), nullable=False),
        sa.Column(
            "snmpv3_sec_level",
            sa.Enum("no_auth_no_priv", "auth_no_priv", "auth_priv", name="snmpseclevel"),
            nullable=True,
        ),
        sa.Column("snmpv3_sec_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("last_config_poll", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("acked_revision", sa.Integer(), nullable=False),
        sa.Column("acked_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("snmpv2c_credential_id", sa.Integer(), nullable=True),
        sa.Column("snmpv3_credential_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["snmpv2c_credential_id"],
            ["credential.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snmpv3_credential_id"],
            ["credential.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collectionagentnodelink",
        sa.Column("collection_agent_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_agent_id"],
            ["collectionagent.id"],
        ),
        sa.ForeignKeyConstraint(["node_id"], ["node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("collection_agent_id", "node_id"),
    )
    op.create_table(
        "lldpneighbor",
        sa.Column("local_interface", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_device", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_interface", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("discovery_protocol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_instance_id", sa.Integer(), nullable=False),
        sa.Column("remote_node_id", sa.Integer(), nullable=True),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_instance_id"], ["node.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["remote_node_id"], ["node.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lldpneighbor_collected_at"), "lldpneighbor", ["collected_at"], unique=False)
    op.create_index(op.f("ix_lldpneighbor_hash"), "lldpneighbor", ["hash"], unique=False)
    op.create_index(op.f("ix_lldpneighbor_node_instance_id"), "lldpneighbor", ["node_instance_id"], unique=False)
    op.create_index(op.f("ix_lldpneighbor_remote_node_id"), "lldpneighbor", ["remote_node_id"], unique=False)
    op.create_table(
        "mgmt_connection",
        sa.Column("primary", sa.Boolean(), nullable=False),
        sa.Column("connection_type", sa.Enum("ssh", "telnet", name="connectiontype"), nullable=False),
        sa.Column("target_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mgmt_connection_node_id"), "mgmt_connection", ["node_id"], unique=False)
    op.create_table(
        "nodecredential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credential.id"],
        ),
        sa.ForeignKeyConstraint(["node_id"], ["node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodecredential_credential_id"), "nodecredential", ["credential_id"], unique=False)
    op.create_index(op.f("ix_nodecredential_node_id"), "nodecredential", ["node_id"], unique=False)
    op.create_table(
        "telemetryagentcapabilitylink",
        sa.Column("telemetry_agent_id", sa.Integer(), nullable=False),
        sa.Column(
            "capability",
            sa.Enum("icmp", "mdt", "snmp", "snmp_trap", "syslog_rfc5424", name="telemetrycapability"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telemetry_agent_id"],
            ["telemetryagent.id"],
        ),
        sa.PrimaryKeyConstraint("telemetry_agent_id", "capability"),
    )
    op.create_table(
        "telemetryagentmatchrule",
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("site", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("vendor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("os", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telemetry_agent_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["telemetry_agent_id"],
            ["telemetryagent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telemetryagentnodelink",
        sa.Column("telemetry_agent_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["telemetry_agent_id"],
            ["telemetryagent.id"],
        ),
        sa.PrimaryKeyConstraint("telemetry_agent_id", "node_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telemetryagentnodelink")
    op.drop_table("telemetryagentmatchrule")
    op.drop_table("telemetryagentcapabilitylink")
    op.drop_index(op.f("ix_nodecredential_node_id"), table_name="nodecredential")
    op.drop_index(op.f("ix_nodecredential_credential_id"), table_name="nodecredential")
    op.drop_table("nodecredential")
    op.drop_index(op.f("ix_mgmt_connection_node_id"), table_name="mgmt_connection")
    op.drop_table("mgmt_connection")
    op.drop_index(op.f("ix_lldpneighbor_remote_node_id"), table_name="lldpneighbor")
    op.drop_index(op.f("ix_lldpneighbor_node_instance_id"), table_name="lldpneighbor")
    op.drop_index(op.f("ix_lldpneighbor_hash"), table_name="lldpneighbor")
    op.drop_index(op.f("ix_lldpneighbor_collected_at"), table_name="lldpneighbor")
    op.drop_table("lldpneighbor")
    op.drop_table("collectionagentnodelink")
    op.drop_table("telemetryagent")
    op.drop_index(op.f("ix_sitecredential_site_name"), table_name="sitecredential")
    op.drop_index(op.f("ix_sitecredential_credential_id"), table_name="sitecredential")
    op.drop_table("sitecredential")
    op.drop_index(op.f("ix_node_created_at"), table_name="node")
    op.drop_table("node")
    op.drop_index(op.f("ix_credentialfield_credential_id"), table_name="credentialfield")
    op.drop_table("credentialfield")
    op.drop_table("collectionagentmatchrule")
    op.drop_table("assetclusterlink")
    op.drop_table("siteregionassignment")
    op.drop_table("site")
    op.drop_table("region")
    op.drop_table("ned")
    op.drop_table("logicalnode")
    op.drop_table("externalvalue")
    op.drop_index(op.f("ix_device_config_node_instance_id"), table_name="device_config")
    op.drop_index(op.f("ix_device_config_hash"), table_name="device_config")
    op.drop_index(op.f("ix_device_config_created_at"), table_name="device_config")
    op.drop_table("device_config")
    op.drop_index(op.f("ix_credential_name"), table_name="credential")
    op.drop_table("credential")
    op.drop_table("contactassignment")
    op.drop_table("contact")
    op.drop_table("collectionagent")
    op.drop_table("assetcluster")
    op.drop_table("asset")
    # ### end Alembic commands ###
