import requests


class RestClient:
    def __init__(self): ...

    def get_item(self, kind: str, id: int): ...
    def query_items(self, kind: str, params: dict, limit: int = 100, cursor: str = None): ...
