[tool.poetry]
name = "acex-driver-fortinet-fortios-cli"
version = "0.1.0"
description = "ACE-X Driver: Fortinet FortiOS CLI"
authors = ["Johan Lahti <johan.lahti@acebit.se>"]
license = "AGPL-3.0"
homepage = "https://github.com/acex-labs/acex"
repository = "https://github.com/acex-labs/acex"

packages = [
    { include = "acex_driver_fortinet_fortios_cli", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.13"
netmiko = "^4.6.0"
jinja2 = "^3.1.6"
acex-devkit = { path = "../../devkit", develop = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."acex.neds"]
fortinet_fortios_cli = "acex_driver_fortinet_fortios_cli.fortios_cli:FortiOSCLIDriver"

[dependency-groups]
dev = [
    "ipython (>=9.10.0,<10.0.0)"
]
