system {
    host-name ams-dc1-leaf-1;
    domain-name dc.example.com;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password "$6$obfuscated";
            }
        }
    }
    services {
        ssh;
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 10.200.0.2/24;
            }
        }
    }
    xe-0/0/0 {
        description "UPLINK-ams-dc1-core-1-xe0/0/0";
        unit 0 {
            family inet {
                address 10.0.0.2/30;
            }
        }
    }
    xe-0/0/1 {
        description "DOWNLINK-Servers-rack-A01-A10";
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
            }
        }
    }
    xe-0/0/2 {
        description "DOWNLINK-Servers-rack-A01-A10";
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
            }
        }
    }
}
routing-options {
    static {
        route 0.0.0.0/0 next-hop 10.200.0.254;
    }
}
