system {
    host-name ams-dc1-leaf-2;
    domain-name dc.example.com;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password "$6$obfuscated";
            }
        }
    }
    services {
        ssh;
    }
}
vlans {
    SERVERS {
        vlan-id 100;
    }
    STORAGE {
        vlan-id 200;
    }
    MANAGEMENT {
        vlan-id 300;
    }
    DMZ {
        vlan-id 400;
    }
    BACKUP {
        vlan-id 500;
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 10.200.0.3/24;
            }
        }
    }
    xe-0/0/0 {
        description "UPLINK-ams-dc1-core-1-xe0/0/1";
        unit 0 {
            family inet {
                address 10.2.0.6/30;
            }
        }
    }
    xe-0/0/1 {
        description "DOWNLINK-Servers-rack-A11-A20";
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
                vlan {
                    members [ SERVERS STORAGE MANAGEMENT DMZ BACKUP ];
                }
            }
        }
    }
    xe-0/0/2 {
        description "DOWNLINK-Servers-rack-A11-A20";
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
                vlan {
                    members [ SERVERS STORAGE MANAGEMENT DMZ BACKUP ];
                }
            }
        }
    }
    irb {
        unit 100 {
            description "SERVERS-gateway";
            family inet {
                address 10.200.101.1/24;
            }
        }
        unit 300 {
            description "MANAGEMENT-gateway";
            family inet {
                address 10.200.0.3/24;
            }
        }
    }
}
routing-options {
    router-id 10.200.0.3;
    static {
        route 0.0.0.0/0 next-hop 10.2.0.5;
    }
}
