hostname sto-dc1-dist-1
!
ip domain-name dc.example.com
!
aaa new-model
username admin privilege 15 secret 9 $9$obfuscated
!
interface Management0
 description OOB-Management
 ip address 10.100.0.2 255.255.255.0
 no shutdown
!
ip route vrf Mgmt-vrf 0.0.0.0 0.0.0.0 10.100.0.254
!
line vty 0 4
 login local
 transport input ssh
!
end