system {
    host-name ams-dc1-core-1;
    domain-name dc.example.com;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password "$6$obfuscated";
            }
        }
    }
    services {
        ssh;
    }
}
vlans {
    SERVERS {
        vlan-id 100;
    }
    STORAGE {
        vlan-id 200;
    }
    MANAGEMENT {
        vlan-id 300;
    }
    DMZ {
        vlan-id 400;
    }
    BACKUP {
        vlan-id 500;
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 10.200.0.1/24;
            }
        }
    }
    et-0/0/0 {
        description "UPLINK-Internet-Router-et0/0/0";
        unit 0 {
            family inet {
                address 10.0.0.1/30;
            }
        }
    }
    xe-0/0/0 {
        description "DOWNLINK-ams-dc1-leaf-1";
        unit 0 {
            family inet {
                address 10.2.0.1/30;
            }
        }
    }
    xe-0/0/1 {
        description "DOWNLINK-ams-dc1-leaf-2";
        unit 0 {
            family inet {
                address 10.2.0.5/30;
            }
        }
    }
    irb {
        unit 300 {
            description "MANAGEMENT-gateway";
            family inet {
                address 10.200.0.1/24;
            }
        }
    }
}
routing-options {
    router-id 10.200.0.1;
    autonomous-system 65010;
    static {
        route 0.0.0.0/0 next-hop 10.0.0.2;
    }
}
